name: Trigger Repo B GitHub workflow
on:
  push:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello 
        run: echo "hahah"
        
  trigger-repob-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7.0.0
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const workflowDispatchResponse = await github.rest.actions.createWorkflowDispatch({
              owner: 'MeraORGhai',
              repo: 'actions-lib',
              workflow_id: 'trigger-me.yml',
              ref: 'dev',
              inputs: {
                param1: 'value1',
              }
            })
            
