# trigger-repob-workflow.yml
name: Trigger Repo B GitHub workflow
on:
  push:
  # workflow_run:
  #   workflows: [trigger-me] # Name of GitHub workflow to trigger in target repository
  #   types:
  #     - completed
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello 
        run: echo "hahah"
        
  trigger-repob-workflow:
    #if: github.event.workflow_run.conclusion == 'success' # Run only when workflow run has succeeded, i.e. all jobs have succeeded
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7.0.0
        with:
          github-token: ${{ secrets.PAT }} # Fine-grained GitHub PAT that was saved as repository secret
          script: |
              const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'MeraORGhai',
              repo: 'actions-lib',
              workflow_id: 'trigger-me.yml',
              ref: 'dev',
              inputs: {
                param1: 'value1',
                param2: 'value2'
                // Add more parameters as needed
              }
            });
            console.log(response);
            return response;
            
      - name: Get Workflow Run Status
        id: get-status
        if: steps.trigger-repob.outputs.id != null
        run: |
          const runId = steps.trigger-repob.outputs.id;
          const { data } = await github.rest.actions.getWorkflowRun({
            owner: 'MeraORGhai',
            repo: 'actions-lib',
            run_id: runId
          });
          console.log(data.status);
          return data.status;




          
      #       await github.rest.actions.createWorkflowDispatch({
      #         owner: 'MeraORGhai',
      #         repo: 'actions-lib',
      #         workflow_id: 'trigger-me.yml',
      #         ref: 'dev',
      #         inputs: {
      #           param1: 'value1',
      #         }
      #       })
      #       const runId = response.data.id; // Extracting the ID of the triggered workflow run
      #       core.setOutput('triggered_run_id', runId); // Setting the output to be used in subsequent steps
            
      # - name: Get Status of Triggered Job
      #   id: get_job_status
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     script: |
      #       const jobStatus = await github.rest.actions.getWorkflowRun({
      #         owner: 'MeraORGhai',
      #         repo: 'actions-lib',
      #         run_id: ${{ steps.trigger-repob-workflow.outputs.triggered_run_id }}
      #       });
      #       console.log(jobStatus.data.status); 

      # - name: Get Status of Triggered Job
      #   id: get_job_status
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     script: |
      #       const response = await github.rest.actions.getWorkflowRun({
      #         owner: 'MeraORGhai',
      #         repo: 'actions-lib',
      #         run_id: ${{ steps.trigger-repob-workflow.outputs.triggered_run_id }}
      #       });
            console.log(response.data.status);
    
