name: Trigger Repo B GitHub workflow
on:
  push:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello 
        run: echo "hahah"
        
  trigger-repob-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: MeraORGhai
          repo: actions-lib
          github_token: ${{ secrets.PAT }}
          #github_user: jayy
          workflow_file_name: trigger-me.yml
          ref: dev
          wait_interval: 10
          client_payload: '{param1:hello}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
      # - uses: actions/github-script@v7.0.0
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     script: |
      #       const workflowDispatchResponse = await github.rest.actions.createWorkflowDispatch({
      #         owner: 'MeraORGhai',
      #         repo: 'actions-lib',
      #         workflow_id: 'trigger-me.yml',
      #         ref: 'dev',
      #         inputs: {
      #           param1: 'value1',
      #         }
      #       })
            
